import Head from "next/head";
import { useEffect, useState } from "react";
import ReactPlayer from "react-player";

export default function Home() {
  const [video, setVideo] = useState(false);

  useEffect(() => {
    setInterval(() => {
      fetch("/api/helloDom")
        .then((res) => res.json())
        .then((res) => {
          if (res.name === "start") {
            console.log(res.name);
            setVideo(true);
          } else {
            console.log(res);
          }
        });
    }, 10000);
  }, []);

  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {video && (
            <ReactPlayer url="https://www.youtube.com/watch?v=LXb3EKWsInQ" />
          )}
        </div>
      </main>
    </>
  );
}
