import Head from "next/head";

export default function Sensor() {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <button
            onClick={() => {
              fetch("/api/helloDom?artem=top&grant=horosh")
                .then((res) => res.json())
                .then((res) => console.log(res));
            }}
          >
            Send INFO to backend
          </button>
        </div>
      </main>
    </>
  );
}
